# This is a basic workflow to help you get started with Actions

name: Slack Notificationのテスト

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Try to fail
        run: exit 1
        
      - name: Echo github.action_path
        run: |
          echo github.action_path: ${{ github.action_path }}
          echo github.event_path: ${{ github.event_path }}
          echo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
          echo $name
      - name: Echo URL and BODY
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          URL=$(gh pr view ${{matrix.branch}} --json url | jq -r ' .url')
          gh pr view ${{matrix.branch}} --json url | jq -r ' .url' | echo
          BODY=$(gh pr view ${{matrix.branch}} --json body | jq -r ' .body')
          gh pr view ${{matrix.branch}} --json body | jq -r ' .body' | echo
          echo ${URL}
          echo ${BODY}
      - name: Echo github info
        run: |
          echo ${{ github.workflow }}
          echo ${{ github.event.pull_request.html_url }}
          echo ${{ github.event.commit_comment.html_url }}
          echo ${{ github.event.commit_comment.body }}
        

      - name: Slack webhook
        if: failure()
        env:
          WORKFLOW: ${GITHUB_WORKFLOW}
          ACTOR: ${GITHUB_ACTOR}
        run: |
          jq -n '{
            "attachments": [
                {
                    "fallback": "E2Eテストが失敗しました。",
                    "mrkdwn_in": [
                        "text"
                    ],
                    "color": "danger",
                    "pretext": ":red_circle: $WORKFLOW",
                    "title": "Dev MemberAPI E2E Test",
                    "text": "結果の詳細は<http://www.example.com|こちら>から参照してください:sob:",
                    "fields": [
                        {
                            "title": "Actor",
                            "value": "$ACTOR",
                            "short": "true"
                        },
                        {
                            "title": "Event Name",
                            "value": "Event Name Value",
                            "short": "true"
                        },
                        {
                            "title": "Action URL",
                            "value": "URL"
                        }
                    ]
                }
            ]}' | curl -H 'Content-Type: application/json' -d @- https://hooks.slack.com/services/${{secrets.SLACK_WEBHOOK}}
